rutas:
  datos: data/housing.csv
  modelo: model.pkl
  mlruns: mlruns

experimento:
  nombre: PreciosVivienda-CICD

division:
  test_size: 0.2
  random_state: 42

modelo:
  algoritmo: GradientBoostingRegressor
  parametros:
    n_estimators: 300
    learning_rate: 0.05
    max_depth: 3
